spring.profiles.active=@activatedProperties@

aws.storage.s3.bucket=ds-shop
aws.storage.s3.access-key=${AWS_S3_ACCESSKEY}
aws.storage.s3.secret-key=${AWS_S3_SECRETKEY}
aws.storage.s3.region=sa-east-1

aws.storage.document.download-url=http://localhost:8080/downloads
aws.storage.image.download-url=https://${aws.storage.s3.bucket}.s3.${aws.storage.s3.region}.amazonaws.com